I18n
wolox-training/jg-rails pull request #14
Opened 2018-07-18 18:12 UTC by jcgrethe

### Summary

- Added internationalization to emails

### Trello card
https://trello.com/c/ep8vkBtl/27-internacionalizar-el-email

### Screenshot
![screenshot from 2018-07-17 18-43-07](https://user-images.githubusercontent.com/26804047/42847098-4844839e-89f1-11e8-84e2-45b89d072bbc.png)
![screenshot from 2018-07-17 18-43-10](https://user-images.githubusercontent.com/26804047/42847099-4866d94e-89f1-11e8-9146-55d9e7fc011f.png)

2018-07-20 16:05 UTC, petaalcala requested changes

2018-07-20 16:05 UTC, santyalcala commented on app/views/rent_mailer/new_rent.html.erb
> +          <th><%= t('book') %></th>
We saw that this translatings really works, but we can order this better.
For the `book` translation, we can make the file for book translations like in these links: 

here for the "automatic" `book` model translations: http://guides.rubyonrails.org/i18n.html#translations-for-active-record-models

And here how we should organize the files: http://guides.rubyonrails.org/i18n.html#organization-of-locale-files

2018-07-20 16:07 UTC, hdf1996 requested changes

2018-07-20 16:07 UTC, hdf1986 commented on app/mailers/rent_mailer.rb
> +    I18n.locale = user.locale
Take care here! This will set the locale for the entire app.

Try with 
```   
 I18n.with_locale(loc) do
      # your code
    end
```

2018-07-23 15:10 UTC, hdf1996 approved these changes

2018-07-23 17:18 UTC, petaalcala requested changes

2018-07-23 17:18 UTC, petaalcala commented on config/locales/models/rent/es.yml
>        attributes:
Be careful here, attributes has the same "level" of model... and then inside we should write like this:
```
attributes:
    rent:
        from: 'Desde'
```

2018-07-23 17:18 UTC, petaalcala commented on config/locales/models/rent/es.yml
>        attributes:
Look this link: http://guides.rubyonrails.org/i18n.html#translations-for-active-record-models

2018-07-23 17:21 UTC, hdf1996 requested changes
Just check the @santyalcala comments :)

2018-07-23 18:34 UTC, hdf1996 approved these changes

2018-07-23 18:36 UTC, merged