added testing for BookSuggestion
wolox-training/jg-rails pull request #19
Opened 2018-07-19 15:19 UTC by jcgrethe

### Summary

- Added testing for BookSuggestion

### Trello card
https://trello.com/c/foAmWY6i/31-crear-test-para-endpoint-de-creaci%C3%B3n-de-un-booksuggestion

2018-07-20 17:26 UTC, petaalcala requested changes

2018-07-20 17:26 UTC, petaalcala commented on spec/controllers/api/v1/book_suggestion_spec.rb
> +        expect do
I know this code is in the card but we can improve this:
Like you see, we are repeating to much this code: 
```
expect do
  post :create, params: { book_suggestion: new_suggestion_attributes }
end
```

So we can do something like this: 
Define `book_creation_request` which will "represent" the request. We can do that like this: `let(:book_creation_request) { post :create, params: { book_suggestion: new_suggestion_attributes } }`

Then, when we used the `post :create, params: { ... ...}`, we can use that `book_creation_request`.

Also, we are using a lot of ` expect do ... end`, now the line will be shorter, so we can try using `{ }`, instead of `do end`

2018-07-23 15:12 UTC, hdf1996 requested changes
Just check the @santyalcala comment :)

2018-07-24 15:02 UTC, hdf1996 approved these changes

2018-07-24 18:23 UTC, merged