added a public view for suggestions
wolox-training/jg-rails pull request #20
Opened 2018-07-20 19:22 UTC by jcgrethe

### Summary

- Added a view to add suggestions

### Trello card 
https://trello.com/c/MOgyJxPi/28-crear-vista-para-crear-book-suggestions
### Screenshots
![screenshot from 2018-07-20 16-18-59](https://user-images.githubusercontent.com/26804047/43021061-b25e4974-8c38-11e8-81a5-411286d13806.png)
![screenshot from 2018-07-20 16-19-06](https://user-images.githubusercontent.com/26804047/43021062-b2859c18-8c38-11e8-95e6-235dfd3eeccd.png)
![screenshot from 2018-07-20 16-19-12](https://user-images.githubusercontent.com/26804047/43021063-b2ab7730-8c38-11e8-95aa-467d5ed4731c.png)

2018-07-23 17:26 UTC, petaalcala requested changes

2018-07-23 17:26 UTC, petaalcala commented on app/views/book_suggestions/new.html.erb
> +    <h1>Author</h1>
Can you use translations for this?
Maybe later, if we have to translate this, using `I18n.t('activerecord.attributes.MODEL.COLUMN)`, in this example model would be book_suggestion and column, author.
That is one of the greatest uses of I18n.

Using

2018-07-24 15:06 UTC, hdf1996 approved these changes

2018-07-24 15:06 UTC, hdf1986 commented on app/views/book_suggestions/new.html.erb
> +      function new_suggestion(){
Im not going to review frontend, but take care about the conventions! if in some case you are going to work with it, make sure that a frontend reviewer is going to review your code

2018-07-24 18:23 UTC, merged